import SwiftUI
import Foundation


struct STGBBTview: View {
    @State var searchTerm: String = ""
    
    var body: some View {
        
        VStack() {
            VStack {
                SearchBar(text: $searchTerm, placeholder: "Suche")
            }
            VStack {
                HStack {
                    Image(systemName: "checkmark.circle.fill")
                        .foregroundColor(.green)
                        .padding(.horizontal)
                    Text("Stand 01.06.2022")
                    Spacer ()
                    HStack {
                        Image(systemName: "link")
                            .foregroundColor(Color.blue)
                        Text("Original Text")
                            .foregroundColor(Color.blue)
                    }
                    .padding(.horizontal)
                    .onTapGesture() {
                        UIApplication.shared.open(URL(string: "https://www.admin.ch/opc/de/classified-compilation/19370083/202007010000/311.0.pdf")!)
                    }
                }
                List {
                    ForEach(gesetzestextSTGBBT.filter {
                        self.searchTerm.isEmpty ? true : $0.buch.localizedCaseInsensitiveContains(searchTerm)
                        || $0.teil.localizedCaseInsensitiveContains(searchTerm)
                        || $0.titel.localizedCaseInsensitiveContains(searchTerm)
                        || $0.kapitel.localizedCaseInsensitiveContains(searchTerm)
                        || $0.abschnitt.localizedCaseInsensitiveContains(searchTerm)
                        || $0.artikel.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginale1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginale2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer3z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer3.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer4z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litaziffer4.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litez.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0lite.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litfz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litf.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litgz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0litg.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0lithz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz0lith.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaziffer3z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litaziffer3.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litabisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litabis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbziffer3z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litbziffer3.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litcbisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litcbis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1lite.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litez.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1lite.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1liteziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1liteziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1liteziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1liteziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1litf.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litfz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litf.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litfbisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litfbis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1litg.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litgz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litg.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1lith.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1lithz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1lith.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1liti.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litiz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1liti.localizedCaseInsensitiveContains(searchTerm)
                        || $0.marginaleabsatz1litj.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litjz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litj.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litkz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litk.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litlz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litl.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litmz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litm.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litnz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litn.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litoz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1lito.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litpz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1litp.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bislitaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bislita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bislitbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bislitb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bislitcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz1bislitc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litabisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litabis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litbbisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litbbis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litez.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lite.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litfz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litf.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litgz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litg.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lithz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lith.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litiz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2liti.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litjz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litj.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litkz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litk.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litlz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litl.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litmz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litm.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litnz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litn.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litoz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lito.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litpz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litp.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litqz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litq.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litrz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litr.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litsz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lits.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2littz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litt.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2lituz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litu.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litvz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2litv.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislitez.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2bislite.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2terz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2ter.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quater.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterlitaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterlita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterlitbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterlitb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterlitcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quaterlitc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quinquiesz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2quinquies.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2sexiesz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2sexies.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2septiesz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz2septies.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litdziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litdziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litdziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3litdziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz3bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litaziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litaziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litaziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litaziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litbziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litbziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litbziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litbziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4bislitaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4bislita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4bislitbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4bislitb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4terz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4ter.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4quaterz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4quater.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4quinquiesz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz4quinquies.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer1z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer1.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer2z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer2.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer3z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer3.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer4z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer4.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer5z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer5.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer6z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer6.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer7z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer7.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer8z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer8.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer9z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litaziffer9.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz5bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litaz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6lita.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litbz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litb.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litcz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litc.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litdz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litd.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litez.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6lite.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litfz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litf.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litgz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6litg.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6lithz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6lith.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz6bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz7z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz7.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz7bisz.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz7bis.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz8z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz8.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz9z.localizedCaseInsensitiveContains(searchTerm)
                        || $0.absatz9.localizedCaseInsensitiveContains(searchTerm)
                    })
                    { item in
                        Part2(gesetzestextSTGBBT: item, searchTerm: self.$searchTerm)
                    }
                } //End of List
                .listStyle(PlainListStyle())
                .id(UUID())
                .gesture(DragGesture().onChanged{_ in UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)})
            } //Closing Master VStack
        }
        .navigationBarTitle(Text("Besonderer Teil (Art. 111-392)"))
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct STGBBTview_Previews: PreviewProvider {
    static var previews: some View {
        Group {
            STGBBTview(searchTerm:(""))
        }
    }
}
